### ISSUE TITLE
Pass env variables to the already build app?

### ISSUE THREAD

**Issue by nanu-c** [mattburrell/vite-react-docker#1]
How can I achieve this?

**Comment by corolol** [comment]
There is a page about that in the Vite documentation: https://vitejs.dev/guide/env-and-mode.html

**Comment by nanu-c** [comment]
That's helpful but not a solution because the vite env variables are build time parameters whereby i would expect to toggle it via the env variables in the container.

**Comment by corolol** [comment]
It also says that:

> In addition, environment variables that already exist when Vite is executed have the highest priority and will not be overwritten by .env files.

So I'm pretty sure that it also imports the global ones and You should be able set some env variables in the container (with VITE_  prefix in the name) and then access it via `import.meta.env`

**Comment by nanu-c** [comment]
With this entrypoint.sh the env vars are replaced
```
#!/bin/sh

ROOT_DIR=/usr/share/nginx/html

# Replace env vars in JavaScript files
api_url=$(echo "$VITE_API_URL" | sed 's/\//\\\//g') 
for file in $ROOT_DIR/assets/index*.js* $ROOT_DIR/index.html;
do
  echo "Processing $file ...";

  sed -i "s/VITE_API_URL_value/$api_url/g" $file 
  sed -i 's|VITE_KEYCLOAK_URL_value|'${VITE_KEYCLOAK_URL}'|g' $file
  sed -i 's|VITE_TOGGLE_value|'${VITE_TOGGLE}'|g' $file

done
```

Corresponding .env.production:
```
VITE_API_URL=VITE_API_URL_value
VITE_KEYCLOAK_URL=VITE_KEYCLOAK_URL_value

#Toggle Lite-Mode
VITE_TOGGLE=VITE_TOGGLE_value
```

**Comment by corolol** [comment]
You don't need to replace env variables with a shell script, vite does it for you on build

You can try something like that in your Dockerfile:
```dockerfile
FROM node:18.14.2-alpine AS app_vite_react

WORKDIR /app

COPY --link ./client/ .
RUN npm i

ENV VITE_API_URL=VITE_API_URL_value
ENV VITE_KEYCLOAK_URL=VITE_KEYCLOAK_URL_value

#Toggle Lite-Mode
ENV VITE_TOGGLE=VITE_TOGGLE_value

RUN npm run build
```

You can access env variables set in Dockerfile like that:
```tsx
function App() {
  return (
    <>
      <ApiUrlContext.Provider value={import.meta.env.VITE_API_URL}>
        {/* ... */}
      </ApiUrlContext.Provider>
    </>
  );
}
```

**Comment by nanu-c** [comment]
Yes this an example for docker build time env vars, I want runtime vars that changes after the build because i don't want to rebuild for staging and multiple production servers. Like:

```
docker build -t nanu/frontend
docker push nanu/frontend
docker run --rm -p  8060:80 -e VITE_API_URL=http://localhost:3000/ -e VITE_KEYCLOAK_URL=http://keycloak:8080/ nanu/frontend
```

**Comment by nanu-c** [comment]
My Dockerfile now looks like this:

```
FROM node:18 as build

WORKDIR /app

COPY package*.json /app/
COPY yarn.lock /app/

RUN yarn
COPY . /app

RUN yarn build

FROM nginx
COPY --from=build /app/dist /usr/share/nginx/html
COPY ./docker/nginx.conf /etc/nginx/conf.d/custom.conf
COPY ./docker/entrypoint.sh /docker-entrypoint.d/10-entrypoint.sh
```

**Comment by corolol** [comment]
I figured it out with docker compose:
```yml
# docker-compose.yml
version: "3.4"

services:
  react:
    image: corolol/my-vite-react-app
    build:
      context: .
      target: app_vite_react
    restart: no
    volumes:
      - dist:/app/dist/
    environment:
      - VITE_API_URL=http://example.com

  apache:
    image: corolol/my-apache-server
    build:
      context: .
      target: app_apache
    depends_on:
      - react
    restart: unless-stopped
    volumes:
      - dist:/usr/local/apache2/htdocs/
    ports:
      # HTTP
      - target: 80
        published: 80
        protocol: tcp

volumes:
  dist:
```
```dockerfile
# Dockerfile
FROM node:18.14.2-alpine AS app_vite_react

WORKDIR /app

COPY --link ./client/ .
RUN npm i

CMD VITE_API_URL=$VITE_API_URL && npm run build


FROM httpd:2.4 AS app_apache

WORKDIR /srv/app
```
You can build your images with command:
`docker compose -f docker-compose.yml up -d --build`

You can also restart your containers with fresh env variables passed from *docker-compose.yml* with:
`docker compose -f docker-compose.yml up -d`
